### PR TITLE
Add Arnab bio to team section

### PR DESCRIPTION
**Pull request by arnab-muhuri**
Please accept my page. 

Arnab

### CODE REVIEW

**Comment by arnab-muhuri** [comment]
@spestana

**Comment by JessicaS11** [comment]
@arnab-muhuri I noticed you opened two PRs (this one and #54) with your bio. Can you please indicate (by closing one of the PRs) which one you would like us to review for including your bio in the website? Let us know if we can provide support for you to complete that step, and then we can move on to reviewing the remaining PR. Thanks!

**Comment by arnab-muhuri** [comment]
> @arnab-muhuri I noticed you opened two PRs (this one and #54) with your bio. Can you please indicate (by closing one of the PRs) which one you would like us to review for including your bio in the website? Let us know if we can provide support for you to complete that step, and then we can move on to reviewing the remaining PR. Thanks!

@JessicaS11 Please accept PR 55.

**Review by JessicaS11 — APPROVED** [review]
Looks great - thanks, Arnab!

**Pull request merged**
